apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikrotik-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mikrotik-api
  template:
    metadata:
      labels:
        app: mikrotik-api
    spec:
      containers:
      - image: arnobdev/mikrotik-api:master-6834a95
        name: mikrotik-api
        ports:
        - containerPort: 4324
