name: Mikrotik Integration

on: 
  push:
    branches:
      -  feature/kube

jobs:
  Deploy:
    name: Mikrotik Integration Deploy Process
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout Action
        uses: actions/checkout@v3

      - id: vars
        name: Get brandh tag
        shell: bash
        run: |
          echo "::set-output name=tag::${GITHUB_REF#refs/heads/}-$(git rev-parse --short HEAD)"
      - id: 'auth'
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_PASSWORD }}

      - id: 'build_and_push'
        name: Build and push image to Docker Hub
        run: |
          docker build . -t arnobdev/mikrotik-api:${{ steps.vars.outputs.tag }}
          docker push arnobdev/mikrotik-api:${{ steps.vars.outputs.tag }}